### ISSUE TITLE
啊？？？

### ISSUE THREAD

**Issue by lingbopro** [Minemetero/Minemetero#1]
你这抄的不行啊，链接都没换（  

![Screenshot_20240614_081128_com.github.android.jpg](https://github.com/Minemetero/Minemetero/assets/148617407/95c665fb-6a27-44ab-9a43-fb95db10f95e)

**Comment by Minemetero** [comment]
a?

**Comment by lingbopro** [comment]
这里的href不应该指向你的repo地址吗…

**Comment by Minemetero** [comment]
学会读题

**Comment by Minemetero** [comment]
我写的是我活跃的仓库

**Comment by Minemetero** [comment]
我在你的仓库我也活跃啊

**Comment by Minemetero** [comment]
这很合理

**Comment by Minemetero** [comment]
我换地址了你那个手机的问题

**Comment by Minemetero** [comment]
oh你说herf啊我现在换了 ：）

**Comment by lingbopro** [comment]
![Screenshot_20240614_082802_com.github.android.jpg](https://github.com/Minemetero/Minemetero/assets/148617407/0b8436a6-f1aa-4077-9f38-8cfe6c263e69)

少个`r`...

**Comment by Minemetero** [comment]
。。。。

**Comment by Minemetero** [comment]
我的的第一个
github-actions[bot]
ahhhhhhhhhhhhhh

**Comment by lingbopro** [comment]
ahh  
我也更新了一下README

**Comment by Minemetero** [comment]
![image_2024-06-14_111048632](https://github.com/Minemetero/Minemetero/assets/156386015/3b8abde4-ea66-4190-83ac-8671e0a16710)
C++真的假的？
或说你的README.md咋连个issue都不让提啊

**Comment by lingbopro** [comment]
> ![image_2024-06-14_111048632](https://github.com/Minemetero/Minemetero/assets/156386015/3b8abde4-ea66-4190-83ac-8671e0a16710)
> C++真的假的？
> 或说你的README.md咋连个issue都不让提啊
> 

GitHub给我创建的，默认就这样  
回头我手动给打开

**Comment by lingbopro** [comment]
> ![image_2024-06-14_111048632](https://github.com/Minemetero/Minemetero/assets/156386015/3b8abde4-ea66-4190-83ac-8671e0a16710)
> C++真的假的？
> 或说你的README.md咋连个issue都不让提啊
> 

C++确实学过一点  
但是就一点…

**Comment by lingbopro** [comment]
现在可以提issue了`:)`

**Comment by Minemetero** [comment]
cool

**Comment by Minemetero** [comment]
你同学天天刷题不实际操作操作？

**Comment by lingbopro** [comment]
> 你同学天天刷题不实际操作操作？

这个这个…你问他啊，我哪知道（
